/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;

/**
 * @author Gustavo, Ítalo, Juliano e Silas. Descrição: Esta classe tem por
 * propósito mostrar a janela principal do programa. Funções presente:
 * ViewPrincipal(); main(); Data de criação: 05/09/2015.
 */
public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ViewEstagiario
     */
    public ViewPrincipal() {
        initComponents();
        setLocationRelativeTo(null);  //Centraliza a janela na tela.
        setResizable(false);  //Evita o redimensionamento da janela.

        //Defini o icone da aplicação na barra de tarefas.
        URL url = this.getClass().getResource("icone.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabelCadastrarPessoa = new javax.swing.JLabel();
        jLabelCadastrarEquipamento = new javax.swing.JLabel();
        jLabelConfiguracoes = new javax.swing.JLabel();
        jLabelPesquisarPessoa = new javax.swing.JLabel();
        jLabelCadastrarReagente = new javax.swing.JLabel();
        jLabelPesquisarReagente = new javax.swing.JLabel();
        jButtonPesquisarPessoa = new javax.swing.JButton();
        jButtonCadastrarReagente = new javax.swing.JButton();
        jButtonPesquisarReagente = new javax.swing.JButton();
        jButtonCadastrarEquipamento = new javax.swing.JButton();
        jButtonPesquisarEquipamento = new javax.swing.JButton();
        jButtonConfiguracoes = new javax.swing.JButton();
        jButtonCadastrarPessoa = new javax.swing.JButton();
        jButtonCadastrarFreezer = new javax.swing.JButton();
        jButtonPesquisarFreezer = new javax.swing.JButton();
        jLabelCadastrarFreezer = new javax.swing.JLabel();
        jLabelPesquisarFreezer = new javax.swing.JLabel();
        jLabelPesquisarEquipamento = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuItemConfiguracoes = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuPessoa = new javax.swing.JMenu();
        jMenuItemCadastrarPessoa = new javax.swing.JMenuItem();
        jMenuItemPesquisarPessoa = new javax.swing.JMenuItem();
        jMenuReagente = new javax.swing.JMenu();
        jMenuItemCadastrarRg = new javax.swing.JMenuItem();
        jMenuItemPesquisarRg = new javax.swing.JMenuItem();
        jMenuEquipamento = new javax.swing.JMenu();
        jMenuItemCadastrarEquip = new javax.swing.JMenuItem();
        jMenuItemPesquisarEquip = new javax.swing.JMenuItem();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuItemAjuda = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenu();
        jMenuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu principal");

        jPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabelCadastrarPessoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCadastrarPessoa.setText("Cadastrar pessoas");

        jLabelCadastrarEquipamento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCadastrarEquipamento.setText("Cadastrar equipamentos");

        jLabelConfiguracoes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelConfiguracoes.setText("Configurações");

        jLabelPesquisarPessoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPesquisarPessoa.setText("Pesquisar pessoas");

        jLabelCadastrarReagente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCadastrarReagente.setText("Cadastrar reagentes");

        jLabelPesquisarReagente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPesquisarReagente.setText("Pesquisar reagentes");

        jButtonPesquisarPessoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisa_pessoa.png"))); // NOI18N
        jButtonPesquisarPessoa.setToolTipText("");
        jButtonPesquisarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarPessoaActionPerformed(evt);
            }
        });

        jButtonCadastrarReagente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/substancia.png"))); // NOI18N
        jButtonCadastrarReagente.setToolTipText("");
        jButtonCadastrarReagente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarReagenteActionPerformed(evt);
            }
        });

        jButtonPesquisarReagente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisa_substancia.png"))); // NOI18N
        jButtonPesquisarReagente.setToolTipText("");
        jButtonPesquisarReagente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarReagenteActionPerformed(evt);
            }
        });

        jButtonCadastrarEquipamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/equipamentos.png"))); // NOI18N
        jButtonCadastrarEquipamento.setToolTipText("");
        jButtonCadastrarEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarEquipamentoActionPerformed(evt);
            }
        });

        jButtonPesquisarEquipamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisa_equipamentos.png"))); // NOI18N
        jButtonPesquisarEquipamento.setToolTipText("");
        jButtonPesquisarEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarEquipamentoActionPerformed(evt);
            }
        });

        jButtonConfiguracoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/configuracoes.png"))); // NOI18N
        jButtonConfiguracoes.setToolTipText("");
        jButtonConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfiguracoesActionPerformed(evt);
            }
        });

        jButtonCadastrarPessoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/estagiarios.png"))); // NOI18N
        jButtonCadastrarPessoa.setToolTipText("");
        jButtonCadastrarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarPessoaActionPerformed(evt);
            }
        });

        jButtonCadastrarFreezer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/freezer.png"))); // NOI18N
        jButtonCadastrarFreezer.setToolTipText("");
        jButtonCadastrarFreezer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarFreezerActionPerformed(evt);
            }
        });

        jButtonPesquisarFreezer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisa_freezer.png"))); // NOI18N
        jButtonPesquisarFreezer.setToolTipText("");
        jButtonPesquisarFreezer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarFreezerActionPerformed(evt);
            }
        });

        jLabelCadastrarFreezer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCadastrarFreezer.setText("Cadastrar no freezer");

        jLabelPesquisarFreezer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPesquisarFreezer.setText("Pesquisar no freezer");

        jLabelPesquisarEquipamento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPesquisarEquipamento.setText(" Pesquisar equipamentos");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jLabelCadastrarFreezer)
                                .addGap(61, 61, 61)
                                .addComponent(jLabelPesquisarFreezer))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPesquisarReagente)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jButtonCadastrarFreezer)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCadastrarEquipamento, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                        .addComponent(jButtonPesquisarFreezer)
                                        .addGap(24, 24, 24))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPesquisarPessoa)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonPesquisarPessoa)
                                .addComponent(jButtonCadastrarEquipamento)))
                        .addGap(25, 25, 25)))
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCadastrarReagente)
                            .addComponent(jButtonPesquisarEquipamento)
                            .addComponent(jButtonConfiguracoes)))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabelConfiguracoes))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabelPesquisarEquipamento))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCadastrarReagente)
                        .addGap(20, 20, 20)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonCadastrarPessoa)
                    .addComponent(jLabelCadastrarPessoa)
                    .addComponent(jButtonPesquisarReagente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPesquisarPessoa)
                    .addComponent(jButtonCadastrarReagente)
                    .addComponent(jButtonCadastrarPessoa))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCadastrarReagente)
                    .addComponent(jLabelPesquisarPessoa)
                    .addComponent(jLabelCadastrarPessoa))
                .addGap(27, 27, 27)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPesquisarReagente)
                    .addComponent(jButtonCadastrarEquipamento)
                    .addComponent(jButtonPesquisarEquipamento))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPesquisarReagente)
                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCadastrarEquipamento)
                        .addComponent(jLabelPesquisarEquipamento)))
                .addGap(27, 27, 27)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonConfiguracoes)
                    .addComponent(jButtonPesquisarFreezer)
                    .addComponent(jButtonCadastrarFreezer))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPesquisarFreezer)
                    .addComponent(jLabelCadastrarFreezer)
                    .addComponent(jLabelConfiguracoes))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jMenuBar.setBackground(new java.awt.Color(255, 255, 255));

        jMenuArquivo.setText("Arquivo");

        jMenuItemConfiguracoes.setText("Configurações");
        jMenuItemConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConfiguracoesActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItemConfiguracoes);

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItemSair);

        jMenuBar.add(jMenuArquivo);

        jMenuPessoa.setText("Pessoas");

        jMenuItemCadastrarPessoa.setText("Cadastrar pessoas");
        jMenuItemCadastrarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarPessoaActionPerformed(evt);
            }
        });
        jMenuPessoa.add(jMenuItemCadastrarPessoa);

        jMenuItemPesquisarPessoa.setText("Pesquisar pessoas");
        jMenuItemPesquisarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesquisarPessoaActionPerformed(evt);
            }
        });
        jMenuPessoa.add(jMenuItemPesquisarPessoa);

        jMenuBar.add(jMenuPessoa);

        jMenuReagente.setText("Reagentes");

        jMenuItemCadastrarRg.setText("Cadastrar reagentes");
        jMenuItemCadastrarRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarRgActionPerformed(evt);
            }
        });
        jMenuReagente.add(jMenuItemCadastrarRg);

        jMenuItemPesquisarRg.setText("Pesquisar reagentes");
        jMenuItemPesquisarRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesquisarRgActionPerformed(evt);
            }
        });
        jMenuReagente.add(jMenuItemPesquisarRg);

        jMenuBar.add(jMenuReagente);

        jMenuEquipamento.setText("Equipamentos");

        jMenuItemCadastrarEquip.setText("Cadastrar equipamentos");
        jMenuItemCadastrarEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarEquipActionPerformed(evt);
            }
        });
        jMenuEquipamento.add(jMenuItemCadastrarEquip);

        jMenuItemPesquisarEquip.setText("Pesquisar equipamentos");
        jMenuItemPesquisarEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesquisarEquipActionPerformed(evt);
            }
        });
        jMenuEquipamento.add(jMenuItemPesquisarEquip);

        jMenuBar.add(jMenuEquipamento);

        jMenuAjuda.setText("Ajuda");

        jMenuItemAjuda.setText("Dúvidas?");
        jMenuItemAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAjudaActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItemAjuda);

        jMenuBar.add(jMenuAjuda);

        jMenuSobre.setText("Sobre");

        jMenuItemSobre.setText("Sobre esse sistema");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenuSobre.add(jMenuItemSobre);

        jMenuBar.add(jMenuSobre);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarPessoaActionPerformed
        ViewPessoa view = new ViewPessoa();
        view.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarPessoaActionPerformed

    private void jButtonPesquisarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarPessoaActionPerformed
        ViewPesquisarPessoas view = new ViewPesquisarPessoas();
        view.setVisible(true);
    }//GEN-LAST:event_jButtonPesquisarPessoaActionPerformed

    private void jButtonCadastrarReagenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarReagenteActionPerformed
        ViewReagente view = new ViewReagente();
        view.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarReagenteActionPerformed

    private void jButtonPesquisarReagenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarReagenteActionPerformed
        ViewPesquisarReagentes view = new ViewPesquisarReagentes();
        view.setVisible(true);
    }//GEN-LAST:event_jButtonPesquisarReagenteActionPerformed

    private void jButtonCadastrarEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarEquipamentoActionPerformed
        ViewEquipamento view = new ViewEquipamento();
        view.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarEquipamentoActionPerformed

    private void jButtonPesquisarEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarEquipamentoActionPerformed
        ViewPesquisarEquipamentos view = new ViewPesquisarEquipamentos();
        view.setVisible(true);
    }//GEN-LAST:event_jButtonPesquisarEquipamentoActionPerformed

    private void jButtonConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfiguracoesActionPerformed
        ViewConfiguracoes view = new ViewConfiguracoes();
        view.setVisible(true);
    }//GEN-LAST:event_jButtonConfiguracoesActionPerformed

    private void jMenuItemConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConfiguracoesActionPerformed
        ViewConfiguracoes view = new ViewConfiguracoes();
        view.setVisible(true);
    }//GEN-LAST:event_jMenuItemConfiguracoesActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemCadastrarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarPessoaActionPerformed
        ViewPessoa view = new ViewPessoa();
        view.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarPessoaActionPerformed

    private void jMenuItemPesquisarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesquisarPessoaActionPerformed
        ViewPesquisarPessoas view = new ViewPesquisarPessoas();
        view.setVisible(true);
    }//GEN-LAST:event_jMenuItemPesquisarPessoaActionPerformed

    private void jMenuItemCadastrarRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarRgActionPerformed
        ViewReagente view = new ViewReagente();
        view.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarRgActionPerformed

    private void jMenuItemPesquisarRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesquisarRgActionPerformed
        ViewPesquisarReagentes view = new ViewPesquisarReagentes();
        view.setVisible(true);
    }//GEN-LAST:event_jMenuItemPesquisarRgActionPerformed

    private void jMenuItemCadastrarEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarEquipActionPerformed
        ViewEquipamento view = new ViewEquipamento();
        view.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarEquipActionPerformed

    private void jMenuItemPesquisarEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesquisarEquipActionPerformed
        ViewPesquisarReagentes view = new ViewPesquisarReagentes();
        view.setVisible(true);
    }//GEN-LAST:event_jMenuItemPesquisarEquipActionPerformed

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        ViewSobre view = new ViewSobre();
        view.setVisible(true);
    }//GEN-LAST:event_jMenuItemSobreActionPerformed

    private void jMenuItemAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAjudaActionPerformed
        ViewAjuda view = new ViewAjuda();
        view.setVisible(true);
    }//GEN-LAST:event_jMenuItemAjudaActionPerformed

    private void jButtonCadastrarFreezerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarFreezerActionPerformed
        ViewFreezer view = new ViewFreezer();
        view.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarFreezerActionPerformed

    private void jButtonPesquisarFreezerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarFreezerActionPerformed
        ViewPesquisarFreezer view = new ViewPesquisarFreezer();
        view.setVisible(true);
    }//GEN-LAST:event_jButtonPesquisarFreezerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarEquipamento;
    private javax.swing.JButton jButtonCadastrarFreezer;
    private javax.swing.JButton jButtonCadastrarPessoa;
    private javax.swing.JButton jButtonCadastrarReagente;
    private javax.swing.JButton jButtonConfiguracoes;
    private javax.swing.JButton jButtonPesquisarEquipamento;
    private javax.swing.JButton jButtonPesquisarFreezer;
    private javax.swing.JButton jButtonPesquisarPessoa;
    private javax.swing.JButton jButtonPesquisarReagente;
    private javax.swing.JLabel jLabelCadastrarEquipamento;
    private javax.swing.JLabel jLabelCadastrarFreezer;
    private javax.swing.JLabel jLabelCadastrarPessoa;
    private javax.swing.JLabel jLabelCadastrarReagente;
    private javax.swing.JLabel jLabelConfiguracoes;
    private javax.swing.JLabel jLabelPesquisarEquipamento;
    private javax.swing.JLabel jLabelPesquisarFreezer;
    private javax.swing.JLabel jLabelPesquisarPessoa;
    private javax.swing.JLabel jLabelPesquisarReagente;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuEquipamento;
    private javax.swing.JMenuItem jMenuItemAjuda;
    private javax.swing.JMenuItem jMenuItemCadastrarEquip;
    private javax.swing.JMenuItem jMenuItemCadastrarPessoa;
    private javax.swing.JMenuItem jMenuItemCadastrarRg;
    private javax.swing.JMenuItem jMenuItemConfiguracoes;
    private javax.swing.JMenuItem jMenuItemPesquisarEquip;
    private javax.swing.JMenuItem jMenuItemPesquisarPessoa;
    private javax.swing.JMenuItem jMenuItemPesquisarRg;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JMenu jMenuPessoa;
    private javax.swing.JMenu jMenuReagente;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JPanel jPanel;
    // End of variables declaration//GEN-END:variables
}
