/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.math.BigInteger;
import java.net.URL;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.JOptionPane;
import jdbc.QueryConfiguracoes;
import pessoa.UsuarioAtual;

/**
 * @author Gustavo, Ítalo, Juliano e Silas. Descrição: Esta classe tem por
 * propósito mostrar uma janela para alteração da senha do usuário logado.
 * Funções presentes: ViewTrocarSenha(); trocarSenha(); main(); Data de criação:
 * 05/09/2015.
 */
public class ViewTrocarSenha extends javax.swing.JFrame {

    /**
     * Creates new form ViewTrocarSenha
     */
    UsuarioAtual usuario = new UsuarioAtual();

    public ViewTrocarSenha() {
        initComponents();
        setLocationRelativeTo(null);  //Centraliza a janela na tela.
        setResizable(false);  //Evita o redimensionamento da janela.

        //Defini o icone da aplicação na barra de tarefas.
        URL url = this.getClass().getResource("icone.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        jPasswordFieldAtual.grabFocus();  //Coloca foco no jTextField.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabelImagem = new javax.swing.JLabel();
        jLabelTrocarSenha = new javax.swing.JLabel();
        jLabelImagemSenha = new javax.swing.JLabel();
        jLabelSenhaAtual = new javax.swing.JLabel();
        jLabelImagemSenha2 = new javax.swing.JLabel();
        jLabelNovaSenha = new javax.swing.JLabel();
        jPasswordFieldAtual = new javax.swing.JPasswordField();
        jPasswordFieldNova = new javax.swing.JPasswordField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Trocar senha");

        jPanel.setBackground(new java.awt.Color(255, 255, 255));
        jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/configuracoes_menor.png"))); // NOI18N
        jPanel.add(jLabelImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 46, -1, -1));

        jLabelTrocarSenha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTrocarSenha.setText("Trocar senha");
        jPanel.add(jLabelTrocarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 69, -1, -1));

        jLabelImagemSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/senha.png"))); // NOI18N
        jPanel.add(jLabelImagemSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 143, -1, -1));

        jLabelSenhaAtual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelSenhaAtual.setText("Senha atual:");
        jPanel.add(jLabelSenhaAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 143, -1, -1));

        jLabelImagemSenha2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/senha.png"))); // NOI18N
        jPanel.add(jLabelImagemSenha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 193, -1, -1));

        jLabelNovaSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNovaSenha.setText("Nova senha:");
        jPanel.add(jLabelNovaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 193, -1, -1));
        jPanel.add(jPasswordFieldAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 143, 111, -1));

        jPasswordFieldNova.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldNovaKeyPressed(evt);
            }
        });
        jPanel.add(jPasswordFieldNova, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 193, 111, -1));

        jButtonSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanel.add(jButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        jButtonLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        jPanel.add(jButtonLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        trocarSenha();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        //Limpa os campos.
        jPasswordFieldAtual.setText("");
        jPasswordFieldNova.setText("");
        //Da foco no jTextField.
        jPasswordFieldAtual.grabFocus();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();  //Fecha a janela atual.
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jPasswordFieldNovaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldNovaKeyPressed
        //Verifica se a tecla apertada corresponde ao Enter.
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonSalvarActionPerformed(null);
        }
    }//GEN-LAST:event_jPasswordFieldNovaKeyPressed

    //Realiza a troca da senha.
    public void trocarSenha() {
        QueryConfiguracoes query = new QueryConfiguracoes();
        String senhaAtual = new String(jPasswordFieldAtual.getPassword());
        String senhaNova = new String(jPasswordFieldNova.getPassword());

        if (usuario.getUsuarioAtual().equals("root")) {
            JOptionPane.showMessageDialog(null, "Não é possível alterar a senha do root.");
            dispose();  //Fecha a janela atual.
        } else {

            //Verifica se a senha digitada tem no mínimo 8 caracteres.
            if (senhaNova.length() >= 8) {

                try {
                    MessageDigest md = MessageDigest.getInstance("MD5");
                    md.update(senhaAtual.getBytes());

                    String keyAtual = new BigInteger(1, md.digest()).toString(16);

                    MessageDigest md2 = MessageDigest.getInstance("MD5");
                    md2.update(senhaNova.getBytes());

                    String keyNova = new BigInteger(1, md2.digest()).toString(16);

                    //Verifica a senha atual.
                    if (query.verificarSenha(usuario.getUsuarioAtual(), keyAtual) == true) {
                        query.trocarSenha(usuario.getUsuarioAtual(), keyNova);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "A senha atual está incorreta.");
                    }
                } catch (NoSuchAlgorithmException ex) {
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro no algoritmo de criptografia. "
                            + "\nDetalhes: " + ex.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(null, "A nova senha inserida possui menos de 8 caracteres."
                        + "\nPor favor, escolha outra senha.");
                jPasswordFieldNova.setText("");
                jPasswordFieldNova.grabFocus();
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTrocarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTrocarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTrocarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTrocarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTrocarSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JLabel jLabelImagemSenha;
    private javax.swing.JLabel jLabelImagemSenha2;
    private javax.swing.JLabel jLabelNovaSenha;
    private javax.swing.JLabel jLabelSenhaAtual;
    private javax.swing.JLabel jLabelTrocarSenha;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPasswordField jPasswordFieldAtual;
    private javax.swing.JPasswordField jPasswordFieldNova;
    // End of variables declaration//GEN-END:variables
}
