/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import pessoa.WebServiceCep;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import jdbc.QueryPessoa;
import operacoes.TransformarCampos;
import operacoes.VerificarData;
import operacoes.FixedLengthDocument;

/**
 * @author Gustavo, Ítalo, Juliano e Silas. Descrição: Esta classe tem por
 * propósito mostrar uma janela para inclusão de uma nova pessoa
 * (Bolsista/Estagiário/Funcionário). Funções presente: ViewPessoa(); buscarCep();
 * limparCampos(); main(); Data de criação: 05/09/2015.
 */
public class ViewPessoa extends javax.swing.JFrame {

    private boolean okEmail;
    String opcoes[] = {"Sim", "Não"};
    String campo;

    /**
     * Creates new form ViewFuncionario
     */
    public ViewPessoa() {
        initComponents();
        setLocationRelativeTo(null);  //Centraliza a janela na tela.
        setResizable(false);  //Evita o redimensionamento da janela.
        jLabelVerificaEmail.setVisible(false);

        //Defini o icone da aplicação na barra de tarefas.
        URL url = this.getClass().getResource("icone.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        jTextFieldNome.grabFocus();  //Coloca foco no jTextField.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelCadastro = new javax.swing.JLabel();
        jLabelPessoa = new javax.swing.JLabel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldProfissao = new verificacao.VerificarCampo("Letras",50);
        jLabelProfissao = new javax.swing.JLabel();
        jFormattedTextFieldEmail = new javax.swing.JFormattedTextField();
        jLabelVerificaEmail = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jComboBoxEstadoCivil = new javax.swing.JComboBox();
        jFormattedTextFieldCelular = new javax.swing.JFormattedTextField();
        jComboBoxSexo = new javax.swing.JComboBox();
        jLabelSexo = new javax.swing.JLabel();
        jComboBoxRelacionamento = new javax.swing.JComboBox();
        jTextFieldNome = new verificacao.VerificarCampo("Letras",50);
        jLabelRelacionamento = new javax.swing.JLabel();
        jLabelDataNasc = new javax.swing.JLabel();
        jLabelEstadoCivil = new javax.swing.JLabel();
        jLabelTelefoneResidencial = new javax.swing.JLabel();
        jLabelTelefoneCelular = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jFormattedTextFieldDataNasc = new javax.swing.JFormattedTextField();
        jFormattedTextFieldResidencial = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabelCEP = new javax.swing.JLabel();
        jTextFieldLogradouro = new verificacao.VerificarCampo("Letras",50);
        jLabelLogradouro = new javax.swing.JLabel();
        jLabelNumero = new javax.swing.JLabel();
        jTextFieldNumero = new verificacao.VerificarCampo("Numeros",3);
        jTextFieldBairro = new verificacao.VerificarCampo("Letras",50);
        jLabelBairro = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jTextFieldCidade = new verificacao.VerificarCampo("Letras",50);
        jLabelEstado = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox();
        jLabelComplemento = new javax.swing.JLabel();
        jTextFieldComplemento = new verificacao.VerificarCampo("Numeros/Letras",50);
        jButtonBuscar = new javax.swing.JButton();
        jFormattedTextFieldCEP = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabelOBS = new javax.swing.JLabel();
        jLabelOBS2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaOBS2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaOBS = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar pessoas");

        jPanel.setBackground(new java.awt.Color(255, 255, 255));

        jButtonSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelCadastro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCadastro.setText("Cadastrar bolsista/estagiário/funcionário");

        jLabelPessoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pessoa_menor.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jTextFieldProfissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 253, 190, -1));

        jLabelProfissao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelProfissao.setText("Profissão");
        jPanel2.add(jLabelProfissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 228, -1, -1));

        jFormattedTextFieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldEmailFocusLost(evt);
            }
        });
        jPanel2.add(jFormattedTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 190, 190, -1));

        jLabelVerificaEmail.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabelVerificaEmail.setForeground(new java.awt.Color(255, 0, 0));
        jLabelVerificaEmail.setText("Verifique o e-mail digitado");
        jPanel2.add(jLabelVerificaEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 166, -1, -1));

        jLabelEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelEmail.setText("E-mail");
        jPanel2.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 162, -1, -1));

        jComboBoxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não declarado", "Solteiro(a)", "Casado(a)", "Divorciado(a)", "Viúvo(a)", "Separado(a)", "Companheiro(a)" }));
        jPanel2.add(jComboBoxEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 115, -1, -1));

        try {
            jFormattedTextFieldCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(jFormattedTextFieldCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 122, -1));

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));
        jPanel2.add(jComboBoxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 115, -1, -1));

        jLabelSexo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSexo.setText("Sexo");
        jPanel2.add(jLabelSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 89, -1, -1));

        jComboBoxRelacionamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bolsista", "Estagiário", "Funcionário" }));
        jPanel2.add(jComboBoxRelacionamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 51, -1, -1));
        jPanel2.add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 51, 356, -1));

        jLabelRelacionamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelRelacionamento.setText("Relacionamento");
        jPanel2.add(jLabelRelacionamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 25, -1, -1));

        jLabelDataNasc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelDataNasc.setText("Data de nascimento");
        jPanel2.add(jLabelDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        jLabelEstadoCivil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelEstadoCivil.setText("Estado civil");
        jPanel2.add(jLabelEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 89, -1, -1));

        jLabelTelefoneResidencial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTelefoneResidencial.setText("Telefone residencial");
        jPanel2.add(jLabelTelefoneResidencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 164, -1, -1));

        jLabelTelefoneCelular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTelefoneCelular.setText("Telefone celular");
        jPanel2.add(jLabelTelefoneCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 164, -1, -1));

        jLabelNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNome.setText("Nome completo");
        jPanel2.add(jLabelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 25, -1, -1));

        try {
            jFormattedTextFieldDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(jFormattedTextFieldDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 122, -1));

        try {
            jFormattedTextFieldResidencial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(jFormattedTextFieldResidencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 122, -1));

        jTabbedPane.addTab("Identificação", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCEP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCEP.setText("CEP");
        jPanel3.add(jLabelCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 25, -1, -1));
        jPanel3.add(jTextFieldLogradouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 113, 201, -1));

        jLabelLogradouro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelLogradouro.setText("Logradouro");
        jPanel3.add(jLabelLogradouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 90, -1, -1));

        jLabelNumero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNumero.setText("Número");
        jPanel3.add(jLabelNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));
        jPanel3.add(jTextFieldNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 113, 69, -1));
        jPanel3.add(jTextFieldBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 113, 131, -1));

        jLabelBairro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelBairro.setText("Bairro");
        jPanel3.add(jLabelBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 90, -1, -1));

        jLabelCidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCidade.setText("Cidade");
        jPanel3.add(jLabelCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 151, -1, -1));
        jPanel3.add(jTextFieldCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 176, 143, -1));

        jLabelEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelEstado.setText("Estado");
        jPanel3.add(jLabelEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 151, -1, -1));

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jPanel3.add(jComboBoxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 176, -1, -1));

        jLabelComplemento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelComplemento.setText("Complemento");
        jPanel3.add(jLabelComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 151, -1, -1));
        jPanel3.add(jTextFieldComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 176, 222, -1));

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 48, -1, -1));

        try {
            jFormattedTextFieldCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCEP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldCEPFocusLost(evt);
            }
        });
        jFormattedTextFieldCEP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldCEPKeyPressed(evt);
            }
        });
        jPanel3.add(jFormattedTextFieldCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 49, 95, -1));

        jTabbedPane.addTab("Endereço", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabelOBS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelOBS.setText("Observações acerca do trabalho desenvolvido");
        jPanel4.add(jLabelOBS);
        jLabelOBS.setBounds(21, 25, 278, 15);

        jLabelOBS2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelOBS2.setText("Demais observações");
        jPanel4.add(jLabelOBS2);
        jLabelOBS2.setBounds(21, 166, 122, 15);

        jTextAreaOBS.setDocument(new FixedLengthDocument(500));
        jTextAreaOBS2.setColumns(20);
        jTextAreaOBS2.setRows(5);
        jScrollPane2.setViewportView(jTextAreaOBS2);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(21, 192, 474, 96);

        jTextAreaOBS.setDocument(new FixedLengthDocument(500));
        jTextAreaOBS.setColumns(20);
        jTextAreaOBS.setRows(5);
        jScrollPane4.setViewportView(jTextAreaOBS);

        jPanel4.add(jScrollPane4);
        jScrollPane4.setBounds(21, 58, 474, 96);

        jTabbedPane.addTab("Observações", jPanel4);

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabelPessoa)
                        .addGap(43, 43, 43)
                        .addComponent(jLabelCadastro)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonCancelar)
                .addGap(18, 18, 18)
                .addComponent(jButtonLimpar)
                .addGap(18, 18, 18)
                .addComponent(jButtonSalvar)
                .addGap(75, 75, 75))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPessoa)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabelCadastro)))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonLimpar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        buscarCep();
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();  //Fecha a janela atual.
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        limparCampos();
        jTextFieldNome.grabFocus();  //Coloca foco no jTextField.
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jFormattedTextFieldCEPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCEPKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buscarCep();
        }
    }//GEN-LAST:event_jFormattedTextFieldCEPKeyPressed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        VerificarData verificarData = new VerificarData();
        String cep = null;
        //Testa se o campo nome não está vazio.
        if (!jTextFieldNome.getText().trim().isEmpty()) {
            //Testa se o campo email foi digitado corretamente ou está vazio.
            if (okEmail == true || jFormattedTextFieldEmail.getText().equals("")) {
                //Testa se a data de nascimento está correta.
                if (verificarData.verificarData(jFormattedTextFieldDataNasc)) {
                    QueryPessoa query = new QueryPessoa();
                    TransformarCampos ob = new TransformarCampos();

                    if (!jFormattedTextFieldCEP.getText().equals("  .   -   ")) {
                        cep = jFormattedTextFieldCEP.getText();
                    }

                    //Realiza a inserção da pessoa (bolsista/estagiário/funcionário).
                    query.inserirPessoa("1", jComboBoxRelacionamento.getSelectedItem().toString(),
                            jTextFieldNome.getText(), jComboBoxSexo.getSelectedItem().toString(),
                            ob.transformarCampo(jFormattedTextFieldDataNasc),
                            jComboBoxEstadoCivil.getSelectedItem().toString(),
                            jFormattedTextFieldEmail.getText(),
                            jFormattedTextFieldResidencial.getText(),
                            jFormattedTextFieldCelular.getText(), jTextFieldProfissao.getText(),
                            cep, jTextFieldLogradouro.getText(),
                            jTextFieldNumero.getText(), jTextFieldBairro.getText(),
                            jTextFieldCidade.getText(),
                            jComboBoxEstado.getSelectedItem().toString(),
                            jTextFieldComplemento.getText(),
                            jTextAreaOBS.getText(), jTextAreaOBS2.getText());

                } else {
                    JOptionPane.showMessageDialog(null, "A data de nascimento digitada é inválida.");
                    jFormattedTextFieldDataNasc.setValue("");
                    jFormattedTextFieldDataNasc.grabFocus();
                    return;
                }

                int i = JOptionPane.showOptionDialog(null,
                        "Você deseja incluir mais pessoas?", "Confirmação", JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[0]);

                if (i == JOptionPane.YES_OPTION) {
                    limparCampos();
                    jTextFieldNome.requestFocus();

                } else {
                    dispose();  //Fecha a janela atual.
                }
            } else {
                JOptionPane.showMessageDialog(null, "O campo e-mail está incorreto.");
                jFormattedTextFieldEmail.grabFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "O campo nome é obrigatório.");
            jTextFieldNome.setText("");
            jTextFieldNome.grabFocus();
        }

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jFormattedTextFieldCEPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCEPFocusLost
        if (jFormattedTextFieldCEP.getText().equals("  .   -   ")) {
            jFormattedTextFieldCEP.setValue("");
        }
    }//GEN-LAST:event_jFormattedTextFieldCEPFocusLost

    private void jFormattedTextFieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldEmailFocusLost
        //Define a expressão regular.
        Pattern p = Pattern.compile("^[\\w-]+(\\.[\\w-]+)*@([\\w-]+\\.)+[a-zA-Z]{2,3}$");

        //Recupera o valor do campo sem os espaços.
        Matcher m = p.matcher(jFormattedTextFieldEmail.getText().trim());

        if (jFormattedTextFieldEmail.getText().equals("")) {
            jLabelVerificaEmail.setVisible(false);
            return;
        }
        //Verifica se está de acordo com o formato.
        if (!m.find()) {
            jFormattedTextFieldEmail.setForeground(Color.red);  //Troca a cor das letras para vermelho.
            okEmail = false;
            jLabelVerificaEmail.setEnabled(true);
            jLabelVerificaEmail.setVisible(true);
        } else {
            jFormattedTextFieldEmail.setForeground(Color.black);  //Troca a cor das letras para preto.
            okEmail = true;
            jLabelVerificaEmail.setEnabled(false);
            jLabelVerificaEmail.setVisible(false);
        }
    }//GEN-LAST:event_jFormattedTextFieldEmailFocusLost

    public void buscarCep() {
        //Faz a busca pelo cep.
        WebServiceCep webServiceCep = WebServiceCep.searchCep(jFormattedTextFieldCEP.getText());
        //A ferramenta de busca ignora qualquer caracter que não seja número.

        //Caso a busca ocorra bem, imprime os resultados.
        if (webServiceCep.wasSuccessful()) {
            jTextFieldLogradouro.setText(webServiceCep.getLogradouroFull());
            jTextFieldCidade.setText(webServiceCep.getCidade());
            jTextFieldBairro.setText(webServiceCep.getBairro());
            jComboBoxEstado.setSelectedItem(webServiceCep.getUf());

            //Caso haja problemas imprime as excessões.
        } else {
            JOptionPane.showMessageDialog(null, "Erro numero: " + webServiceCep.getResulCode());
            JOptionPane.showMessageDialog(null, "Descrição do erro: " + webServiceCep.getResultText());
        }
    }

    //Limpa os campos da janela.
    public void limparCampos() {
        jComboBoxRelacionamento.setSelectedIndex(0);
        jTextFieldNome.setText("");
        jComboBoxSexo.setSelectedIndex(0);
        jFormattedTextFieldDataNasc.setValue("");
        jComboBoxEstadoCivil.setSelectedIndex(0);
        jFormattedTextFieldEmail.setValue("");
        jFormattedTextFieldResidencial.setValue("");
        jFormattedTextFieldCelular.setValue("");
        jTextFieldProfissao.setText("");
        jFormattedTextFieldCEP.setValue("");
        jTextFieldLogradouro.setText("");
        jTextFieldNumero.setText("");
        jTextFieldBairro.setText("");
        jTextFieldCidade.setText("");
        jTextFieldComplemento.setText("");
        jTextAreaOBS.setText("");
        jTextAreaOBS2.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPessoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxEstado;
    private javax.swing.JComboBox jComboBoxEstadoCivil;
    private javax.swing.JComboBox jComboBoxRelacionamento;
    private javax.swing.JComboBox jComboBoxSexo;
    private javax.swing.JFormattedTextField jFormattedTextFieldCEP;
    private javax.swing.JFormattedTextField jFormattedTextFieldCelular;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNasc;
    private javax.swing.JFormattedTextField jFormattedTextFieldEmail;
    private javax.swing.JFormattedTextField jFormattedTextFieldResidencial;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCEP;
    private javax.swing.JLabel jLabelCadastro;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelComplemento;
    private javax.swing.JLabel jLabelDataNasc;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelEstadoCivil;
    private javax.swing.JLabel jLabelLogradouro;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelOBS;
    private javax.swing.JLabel jLabelOBS2;
    private javax.swing.JLabel jLabelPessoa;
    private javax.swing.JLabel jLabelProfissao;
    private javax.swing.JLabel jLabelRelacionamento;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelTelefoneCelular;
    private javax.swing.JLabel jLabelTelefoneResidencial;
    private javax.swing.JLabel jLabelVerificaEmail;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextArea jTextAreaOBS;
    private javax.swing.JTextArea jTextAreaOBS2;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldComplemento;
    private javax.swing.JTextField jTextFieldLogradouro;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldProfissao;
    // End of variables declaration//GEN-END:variables
}
