/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import jdbc.QueryReagente;
import operacoes.TransformarCampos;
import operacoes.VerificarData;
import operacoes.FixedLengthDocument;

/**
 * @author Gustavo, Ítalo, Juliano e Silas. Descrição: Esta classe tem por
 * propósito mostrar uma janela para edição de uma reagente específico. Funções
 * presente: ViewEditarReagente(); ViewEditarReagente(String item);
 * limparCampos(); carregarDados(); main(); Data de criação: 05/09/2015.
 */
public class ViewEditarReagente extends javax.swing.JFrame {

    String opcoes[] = {"Sim", "Não"};
    String item;
    String campo;

    /**
     * Creates new form ViewEquipamento
     */
    public ViewEditarReagente() {
        initComponents();
        setLocationRelativeTo(null);  //Centraliza a janela na tela.
        setResizable(false);  //Evita o redimensionamento da janela.

        //Defini o icone da aplicação na barra de tarefas.
        URL url = this.getClass().getResource("icone.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        jTextFieldNome.grabFocus();  //Coloca foco no jTextField.
    }

    public ViewEditarReagente(String item) {
        initComponents();
        setLocationRelativeTo(null);  //Centraliza a janela na tela.
        setResizable(false);  //Evita o redimensionamento da janela.

        //Defini o icone da aplicação na barra de tarefas.
        URL url = this.getClass().getResource("icone.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        jTextFieldNome.grabFocus();  //Coloca foco no jTextField.
        this.item = item;
        carregarDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabelEditarReagente = new javax.swing.JLabel();
        jLabelImagem = new javax.swing.JLabel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldNome = new verificacao.VerificarCampo("Numeros/Letras",50);
        jLabelNome = new javax.swing.JLabel();
        jLabelEntrada = new javax.swing.JLabel();
        jLabelValidade = new javax.swing.JLabel();
        jLabelMarca = new javax.swing.JLabel();
        jTextFieldMarca = new verificacao.VerificarCampo("Numeros/Letras",50);
        jLabelApresentacao = new javax.swing.JLabel();
        jTextFieldApresentacao = new verificacao.VerificarCampo("Numeros/Letras",20);
        jLabelLote = new javax.swing.JLabel();
        jTextFieldLote = new verificacao.VerificarCampo("Numeros/Letras",20);
        jLabelQuantidade = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox();
        jTextFieldQuantidade = new verificacao.VerificarCampo("Numeros",3);
        jLabelPoliciaFederal = new javax.swing.JLabel();
        jLabelSaida = new javax.swing.JLabel();
        jFormattedTextFieldEntrada = new javax.swing.JFormattedTextField();
        jFormattedTextFieldValidade = new javax.swing.JFormattedTextField();
        jComboBoxPoliciaFederal = new javax.swing.JComboBox();
        jFormattedTextFieldSaida = new javax.swing.JFormattedTextField();
        jCheckBoxDescartado = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabelOBS = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        jTextAreaOBS = new javax.swing.JTextArea();
        jButtonSalvar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar reagente");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabelEditarReagente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelEditarReagente.setText("Editar reagente");

        jLabelImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/substancia_menor.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNome.setText("Nome");

        jLabelEntrada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelEntrada.setText("Entrada");

        jLabelValidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelValidade.setText("Validade");

        jLabelMarca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelMarca.setText("Marca");

        jLabelApresentacao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelApresentacao.setText("Apresentação");

        jLabelLote.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelLote.setText("Lote");

        jLabelQuantidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelQuantidade.setText("Quantidade");

        jLabelTipo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTipo.setText("Tipo de reagente");

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Líquido", "Sólido" }));

        jLabelPoliciaFederal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPoliciaFederal.setText("Polícia Federal");

        jLabelSaida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSaida.setText("Saída");

        try {
            jFormattedTextFieldEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldEntrada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldEntradaFocusLost(evt);
            }
        });

        try {
            jFormattedTextFieldValidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldValidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldValidadeFocusLost(evt);
            }
        });

        jComboBoxPoliciaFederal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Sim" }));

        try {
            jFormattedTextFieldSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jCheckBoxDescartado.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxDescartado.setText("Descartado");
        jCheckBoxDescartado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDescartadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jComboBoxPoliciaFederal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxDescartado)
                            .addComponent(jFormattedTextFieldSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelNome)
                                .addGap(242, 242, 242)
                                .addComponent(jLabelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelMarca))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldApresentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelApresentacao))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelLote)
                                    .addComponent(jTextFieldLote, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEntrada)
                            .addComponent(jLabelPoliciaFederal))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSaida)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelValidade)
                                .addGap(87, 87, 87)
                                .addComponent(jLabelQuantidade))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jFormattedTextFieldValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipo)
                    .addComponent(jLabelNome))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMarca)
                    .addComponent(jLabelApresentacao)
                    .addComponent(jLabelLote))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldApresentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabelEntrada))
                    .addComponent(jLabelValidade)
                    .addComponent(jLabelQuantidade))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextFieldEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPoliciaFederal)
                    .addComponent(jLabelSaida))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPoliciaFederal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxDescartado)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Identificação", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabelOBS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelOBS.setText("Observações acerca do reagente");
        jPanel3.add(jLabelOBS);
        jLabelOBS.setBounds(21, 25, 197, 15);

        jTextAreaOBS.setDocument(new FixedLengthDocument(500));
        jTextAreaOBS.setColumns(20);
        jTextAreaOBS.setRows(5);
        jScrollPane.setViewportView(jTextAreaOBS);

        jPanel3.add(jScrollPane);
        jScrollPane.setBounds(21, 58, 376, 96);

        jTabbedPane.addTab("Observações", jPanel3);

        jButtonSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelImagem)
                .addGap(55, 55, 55)
                .addComponent(jLabelEditarReagente)
                .addContainerGap(271, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelar)
                .addGap(18, 18, 18)
                .addComponent(jButtonLimpar)
                .addGap(18, 18, 18)
                .addComponent(jButtonSalvar)
                .addGap(80, 80, 80))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelImagem)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabelEditarReagente)))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonLimpar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();  //Fecha a janela atual.
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        VerificarData verificarData = new VerificarData();
        //Testa se o campo nome não está vazio.
        if (!jTextFieldNome.getText().trim().isEmpty()) {
            //Testa se as datas estão corretas.
            if (verificarData.verificarData(jFormattedTextFieldEntrada)
                    && verificarData.verificarData(jFormattedTextFieldValidade)
                    && verificarData.verificarData(jFormattedTextFieldSaida)) {
                QueryReagente query = new QueryReagente();
                TransformarCampos ob = new TransformarCampos();

                //Realiza a atualização do reagente.
                query.atualizarReagente("1", item, jTextFieldNome.getText(),
                        jComboBoxTipo.getSelectedItem().toString(), jTextFieldMarca.getText(),
                        jTextFieldApresentacao.getText(), jTextFieldLote.getText(),
                        ob.transformarCampo(jFormattedTextFieldEntrada),
                        ob.transformarCampo(jFormattedTextFieldValidade), jTextFieldQuantidade.getText(),
                        jComboBoxPoliciaFederal.getSelectedItem().toString(),
                        ob.transformarCampo(jFormattedTextFieldSaida), jTextAreaOBS.getText());

                dispose();  //Fecha a janela atual.
            } else {
                JOptionPane.showMessageDialog(null, "Os campos de entrada, "
                        + "validade ou saída foram digitados incorretamente");
            }

        } else {
            JOptionPane.showMessageDialog(null, "O campo nome é obrigatório.");
            jTextFieldNome.setText("");
            jTextFieldNome.grabFocus();
        }

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        limparCampos();
        jTextFieldNome.grabFocus();  //Coloca foco no jTextField.
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jFormattedTextFieldEntradaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldEntradaFocusLost
        if (jFormattedTextFieldEntrada.getText().equals("  /  /    ")) {
            jFormattedTextFieldEntrada.setValue("");
        }
    }//GEN-LAST:event_jFormattedTextFieldEntradaFocusLost

    private void jFormattedTextFieldValidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldValidadeFocusLost
        if (jFormattedTextFieldValidade.getText().equals("  /  /    ")) {
            jFormattedTextFieldValidade.setValue("");
        }
    }//GEN-LAST:event_jFormattedTextFieldValidadeFocusLost

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        ViewPesquisarReagentes view = new ViewPesquisarReagentes();
        view.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jCheckBoxDescartadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDescartadoActionPerformed
        if (jCheckBoxDescartado.isSelected()) {
            jFormattedTextFieldSaida.setValue("00/00/0000");
            jFormattedTextFieldSaida.setEditable(false);
        } else {
            jFormattedTextFieldSaida.setValue("");
            jFormattedTextFieldSaida.setEditable(true);
            jFormattedTextFieldSaida.grabFocus();
        }
    }//GEN-LAST:event_jCheckBoxDescartadoActionPerformed

    //Limpa os campos da janela.
    public void limparCampos() {
        jTextFieldNome.setText("");
        jComboBoxTipo.setSelectedIndex(0);
        jTextFieldMarca.setText("");
        jTextFieldApresentacao.setText("");
        jTextFieldLote.setText("");
        jFormattedTextFieldEntrada.setValue("");
        jFormattedTextFieldValidade.setValue("");
        jTextFieldQuantidade.setText("");
        jComboBoxPoliciaFederal.setSelectedIndex(0);
        jFormattedTextFieldSaida.setText("");
        jTextAreaOBS.setText("");
    }

    //Transforma a data para ser aceita no banco de dados.
    public String transformarCampos(JFormattedTextField jformatted) {

        campo = jformatted.getText();

        if (!campo.equals("  /  /    ")) {

            String d1 = Character.toString(campo.charAt(0));
            String d2 = Character.toString(campo.charAt(1));
            String m1 = Character.toString(campo.charAt(3));
            String m2 = Character.toString(campo.charAt(4));
            String y1 = Character.toString(campo.charAt(6));
            String y2 = Character.toString(campo.charAt(7));
            String y3 = Character.toString(campo.charAt(8));
            String y4 = Character.toString(campo.charAt(9));

            return y1 + y2 + y3 + y4 + "-" + m1 + m2 + "-" + d1 + d2;
        }
        return null;
    }

    //Carrega os dados do banco na janela para evitar a reinserção de todos os dados.
    public void carregarDados() {
        QueryReagente query = new QueryReagente();

        ResultSet rs;
        rs = query.retornarCamposReagente(item);

        try {
            while (rs.next()) {
                jTextFieldNome.setText(rs.getString("nome_rg"));
                jComboBoxTipo.setSelectedItem(rs.getString("tipo_rg"));
                jTextFieldMarca.setText(rs.getString("marca_rg"));
                jTextFieldApresentacao.setText(rs.getString("apresentacao_rg"));
                jTextFieldLote.setText(rs.getString("lote_rg"));
                jFormattedTextFieldEntrada.setText(rs.getString("entrada_rg"));
                jFormattedTextFieldValidade.setText(rs.getString("validade_rg"));
                jTextFieldQuantidade.setText(rs.getString("quantidade_rg"));
                jComboBoxPoliciaFederal.setSelectedItem(rs.getString("pf_rg"));
                jFormattedTextFieldSaida.setText(rs.getString("saida_rg"));
                jTextAreaOBS.setText(rs.getString("obs_rg"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro de SQL. "
                    + "\nDetalhes: " + ex.getMessage());
        }

        if (jFormattedTextFieldSaida.getText().equals("00/00/0000")) {
            jCheckBoxDescartado.setSelected(true);
            jFormattedTextFieldSaida.setEditable(false);
        }

        if (jFormattedTextFieldEntrada.getText().equals("  /  /    ")) {
            jFormattedTextFieldEntrada.setValue("");
        }

        if (jFormattedTextFieldValidade.getText().equals("  /  /    ")) {
            jFormattedTextFieldValidade.setValue("");
        }

        if (jFormattedTextFieldSaida.getText().equals("  /  /    ")) {
            jFormattedTextFieldSaida.setValue("");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEditarReagente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEditarReagente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEditarReagente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEditarReagente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEditarReagente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JCheckBox jCheckBoxDescartado;
    private javax.swing.JComboBox jComboBoxPoliciaFederal;
    private javax.swing.JComboBox jComboBoxTipo;
    private javax.swing.JFormattedTextField jFormattedTextFieldEntrada;
    private javax.swing.JFormattedTextField jFormattedTextFieldSaida;
    private javax.swing.JFormattedTextField jFormattedTextFieldValidade;
    private javax.swing.JLabel jLabelApresentacao;
    private javax.swing.JLabel jLabelEditarReagente;
    private javax.swing.JLabel jLabelEntrada;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JLabel jLabelLote;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelOBS;
    private javax.swing.JLabel jLabelPoliciaFederal;
    private javax.swing.JLabel jLabelQuantidade;
    private javax.swing.JLabel jLabelSaida;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelValidade;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextArea jTextAreaOBS;
    private javax.swing.JTextField jTextFieldApresentacao;
    private javax.swing.JTextField jTextFieldLote;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldQuantidade;
    // End of variables declaration//GEN-END:variables
}
