/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import pessoa.WebServiceCep;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import jdbc.QueryPessoa;
import operacoes.TransformarCampos;
import operacoes.VerificarData;
import operacoes.FixedLengthDocument;

/**
 * @author Gustavo, Ítalo, Juliano e Silas. Descrição: Esta classe tem por
 * propósito mostrar uma janela para edição de uma pessoa específica. Funções
 * presente: ViewEditarPessoa(); ViewEditarPessoa(String item); buscarCep();
 * limparCampos(); carregarDados(); main(); Data de criação: 05/09/2015.
 */
public class ViewEditarPessoa extends javax.swing.JFrame {

    private boolean okEmail = true;
    String opcoes[] = {"Sim", "Não"};
    String item;

    /**
     * Creates new form ViewFuncionario
     */
    public ViewEditarPessoa() {
        initComponents();
        setLocationRelativeTo(null);  //Centraliza a janela na tela.
        setResizable(false);  //Evita o  redimensionamento da janela.
        jLabelVerificaEmail.setVisible(false);

        //Defini o icone da aplicação na barra de tarefas.
        URL url = this.getClass().getResource("icone.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        jTextFieldNome.grabFocus();  //Coloca foco no jTextField.
    }

    public ViewEditarPessoa(String item) {
        initComponents();
        setLocationRelativeTo(null);  //Centraliza a janela na tela.
        setResizable(false);  //Evita o  redimensionamento da janela.
        jLabelVerificaEmail.setVisible(false);

        //Defini o icone da aplicação na barra de tarefas.
        URL url = this.getClass().getResource("icone.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        jTextFieldNome.grabFocus();  //Coloca foco no jTextField.
        this.item = item;
        carregarDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelEditarPessoa = new javax.swing.JLabel();
        jLabelImagem = new javax.swing.JLabel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldProfissao = new verificacao.VerificarCampo("Letras",50);
        jLabelProfissao = new javax.swing.JLabel();
        jFormattedTextFieldEmail = new javax.swing.JFormattedTextField();
        jLabelVerificaEmail = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jFormattedTextFieldResidencial = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCelular = new javax.swing.JFormattedTextField();
        jComboBoxEstadoCivil = new javax.swing.JComboBox();
        jComboBoxSexo = new javax.swing.JComboBox();
        jLabelSexo = new javax.swing.JLabel();
        jComboBoxRelacionamento = new javax.swing.JComboBox();
        jTextFieldNome = new verificacao.VerificarCampo("Letras",50);
        jLabelRelacionamento = new javax.swing.JLabel();
        jLabelEstadoCivil = new javax.swing.JLabel();
        jLabelTelefoneResidencial = new javax.swing.JLabel();
        jLabelTelefoneCelular = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jFormattedTextFieldDataNasc = new javax.swing.JFormattedTextField();
        jLabelDataNasc = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelCEP = new javax.swing.JLabel();
        jTextFieldLogradouro = new verificacao.VerificarCampo("Letras",50);
        jLabelLogradouro = new javax.swing.JLabel();
        jLabelNumero = new javax.swing.JLabel();
        jTextFieldNumero = new verificacao.VerificarCampo("Numeros",5);
        jTextFieldBairro = new verificacao.VerificarCampo("Letras",50);
        jLabelBairro = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jTextFieldCidade = new verificacao.VerificarCampo("Letras",50);
        jLabelEstado = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox();
        jLabelComplemento = new javax.swing.JLabel();
        jTextFieldComplemento = new verificacao.VerificarCampo("Numeros/Letras",50);
        jButtonBuscar = new javax.swing.JButton();
        jFormattedTextFieldCEP = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabelOBS = new javax.swing.JLabel();
        jLabelOBS2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaOBS2 = new javax.swing.JTextArea();
        jScrollPane = new javax.swing.JScrollPane();
        jTextAreaOBS = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar pessoa");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel.setBackground(new java.awt.Color(255, 255, 255));

        jButtonSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelEditarPessoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelEditarPessoa.setText("Editar bolsista/estagiário/funcionário");

        jLabelImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pessoa_menor.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jTextFieldProfissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 253, 190, -1));

        jLabelProfissao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelProfissao.setText("Profissão");
        jPanel2.add(jLabelProfissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 228, -1, -1));

        jFormattedTextFieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldEmailFocusLost(evt);
            }
        });
        jPanel2.add(jFormattedTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 190, 190, -1));

        jLabelVerificaEmail.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabelVerificaEmail.setForeground(new java.awt.Color(255, 0, 0));
        jLabelVerificaEmail.setText("Verifique o e-mail digitado");
        jPanel2.add(jLabelVerificaEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 166, -1, -1));

        jLabelEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelEmail.setText("E-mail");
        jPanel2.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 162, -1, -1));

        try {
            jFormattedTextFieldResidencial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldResidencial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldResidencialFocusLost(evt);
            }
        });
        jPanel2.add(jFormattedTextFieldResidencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 190, 119, -1));

        try {
            jFormattedTextFieldCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCelular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldCelularFocusLost(evt);
            }
        });
        jPanel2.add(jFormattedTextFieldCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 190, 119, -1));

        jComboBoxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não declarado", "Solteiro(a)", "Casado(a)", "Divorciado(a)", "Viúvo(a)", "Separado(a)", "Companheiro(a)" }));
        jPanel2.add(jComboBoxEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 115, -1, -1));

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));
        jPanel2.add(jComboBoxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 115, -1, -1));

        jLabelSexo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSexo.setText("Sexo");
        jPanel2.add(jLabelSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 89, -1, -1));

        jComboBoxRelacionamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bolsista", "Estagiário", "Funcionário" }));
        jPanel2.add(jComboBoxRelacionamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 51, -1, -1));
        jPanel2.add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 51, 356, -1));

        jLabelRelacionamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelRelacionamento.setText("Relacionamento");
        jPanel2.add(jLabelRelacionamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 25, -1, -1));

        jLabelEstadoCivil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelEstadoCivil.setText("Estado civil");
        jPanel2.add(jLabelEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 89, -1, -1));

        jLabelTelefoneResidencial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTelefoneResidencial.setText("Telefone residencial");
        jPanel2.add(jLabelTelefoneResidencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 164, -1, -1));

        jLabelTelefoneCelular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTelefoneCelular.setText("Telefone celular");
        jPanel2.add(jLabelTelefoneCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 164, -1, -1));

        jLabelNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNome.setText("Nome completo");
        jPanel2.add(jLabelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 25, -1, -1));

        try {
            jFormattedTextFieldDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(jFormattedTextFieldDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 122, -1));

        jLabelDataNasc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelDataNasc.setText("Data de nascimento");
        jPanel2.add(jLabelDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        jTabbedPane.addTab("Identificação", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabelCEP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCEP.setText("CEP");

        jLabelLogradouro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelLogradouro.setText("Logradouro");

        jLabelNumero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNumero.setText("Número");

        jLabelBairro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelBairro.setText("Bairro");

        jLabelCidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCidade.setText("Cidade");

        jLabelEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelEstado.setText("Estado");

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N/A", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jLabelComplemento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelComplemento.setText("Complemento");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCEP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldCEPFocusLost(evt);
            }
        });
        jFormattedTextFieldCEP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldCEPKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelLogradouro)
                        .addGap(147, 147, 147)
                        .addComponent(jLabelNumero)
                        .addGap(44, 44, 44)
                        .addComponent(jLabelBairro))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFieldLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelCidade)
                        .addGap(118, 118, 118)
                        .addComponent(jLabelEstado)
                        .addGap(21, 21, 21)
                        .addComponent(jLabelComplemento))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jFormattedTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscar))
                    .addComponent(jLabelCEP)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelCEP)
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jFormattedTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonBuscar))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLogradouro)
                    .addComponent(jLabelNumero)
                    .addComponent(jLabelBairro))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCidade)
                    .addComponent(jLabelEstado)
                    .addComponent(jLabelComplemento))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane.addTab("Endereço", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabelOBS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelOBS.setText("Observações acerca do trabalho desenvolvido");
        jPanel4.add(jLabelOBS);
        jLabelOBS.setBounds(21, 25, 278, 15);

        jLabelOBS2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelOBS2.setText("Demais observações");
        jPanel4.add(jLabelOBS2);
        jLabelOBS2.setBounds(21, 166, 122, 15);

        jTextAreaOBS.setDocument(new FixedLengthDocument(500));
        jTextAreaOBS2.setColumns(20);
        jTextAreaOBS2.setRows(5);
        jScrollPane2.setViewportView(jTextAreaOBS2);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(21, 192, 474, 96);

        jTextAreaOBS.setDocument(new FixedLengthDocument(500));
        jTextAreaOBS.setColumns(20);
        jTextAreaOBS.setRows(5);
        jScrollPane.setViewportView(jTextAreaOBS);

        jPanel4.add(jScrollPane);
        jScrollPane.setBounds(21, 58, 474, 96);

        jTabbedPane.addTab("Observações", jPanel4);

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabelImagem)
                        .addGap(41, 41, 41)
                        .addComponent(jLabelEditarPessoa))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalvar)
                        .addGap(64, 64, 64)))
                .addGap(10, 10, 10))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelImagem)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabelEditarPessoa)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonSalvar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        buscarCep();
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();  //Fecha a janela atual.
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        limparCampos();
        jTextFieldNome.grabFocus();  //Coloca foco no jTextField.
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        VerificarData verificarData = new VerificarData();
        //Testa se o campo nome não está vazio.
        if (!jTextFieldNome.getText().trim().isEmpty()) {
            //Testa se o campo email foi digitado corretamente ou está vazio.
            if (okEmail == true || jFormattedTextFieldEmail.getText().equals("")) {
                //Testa se a data de nascimento está correta.
                if (verificarData.verificarData(jFormattedTextFieldDataNasc)) {
                    QueryPessoa query = new QueryPessoa();
                    TransformarCampos ob = new TransformarCampos();

                    //Realiza a atualização da pessoa.
                    query.atualizarPessoa("1", item,
                            jComboBoxRelacionamento.getSelectedItem().toString(),
                            jTextFieldNome.getText(), jComboBoxSexo.getSelectedItem().toString(),
                            ob.transformarCampo(jFormattedTextFieldDataNasc),
                            jComboBoxEstadoCivil.getSelectedItem().toString(),
                            jFormattedTextFieldEmail.getText(),
                            jFormattedTextFieldResidencial.getText(),
                            jFormattedTextFieldCelular.getText(), jTextFieldProfissao.getText(),
                            jFormattedTextFieldCEP.getText(), jTextFieldLogradouro.getText(),
                            jTextFieldNumero.getText(), jTextFieldBairro.getText(),
                            jTextFieldCidade.getText(),
                            jComboBoxEstado.getSelectedItem().toString(),
                            jTextFieldComplemento.getText(),
                            jTextAreaOBS.getText(), jTextAreaOBS2.getText());

                    dispose();  //Fecha a janela atual.
                } else {
                    JOptionPane.showMessageDialog(null, "A data de nascimento digitada é inválida.");
                    jFormattedTextFieldDataNasc.setValue("");
                    jFormattedTextFieldDataNasc.grabFocus();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Verifique o email digitado.");
                jFormattedTextFieldEmail.grabFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "O campo nome é obrigatório.");
            jTextFieldNome.setText("");
            jTextFieldNome.grabFocus();
        }

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        ViewPesquisarPessoas view = new ViewPesquisarPessoas();
        view.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jFormattedTextFieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldEmailFocusLost
        //Define a expressão regular.
        Pattern p = Pattern.compile("^[\\w-]+(\\.[\\w-]+)*@([\\w-]+\\.)+[a-zA-Z]{2,3}$");

        //Recupera o valor do campo sem os espaços.
        Matcher m = p.matcher(jFormattedTextFieldEmail.getText().trim());

        if (jFormattedTextFieldEmail.getText().equals("")) {
            jLabelVerificaEmail.setVisible(false);
            return;
        }
        //Verifica se está de acordo com o formato.
        if (!m.find()) {
            jFormattedTextFieldEmail.setForeground(Color.red);  //Troca a cor das letras para vermelho.
            okEmail = false;
            jLabelVerificaEmail.setEnabled(true);
            jLabelVerificaEmail.setVisible(true);
        } else {
            jFormattedTextFieldEmail.setForeground(Color.black);  //Troca a cor das letras para preto.
            okEmail = true;
            jLabelVerificaEmail.setEnabled(false);
            jLabelVerificaEmail.setVisible(false);
        }
    }//GEN-LAST:event_jFormattedTextFieldEmailFocusLost

    private void jFormattedTextFieldResidencialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldResidencialFocusLost
        if (jFormattedTextFieldResidencial.getText().equals("(  )     -    ")) {
            jFormattedTextFieldResidencial.setValue("");
        }
    }//GEN-LAST:event_jFormattedTextFieldResidencialFocusLost

    private void jFormattedTextFieldCelularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCelularFocusLost
        if (jFormattedTextFieldCelular.getText().equals("(  )     -    ")) {
            jFormattedTextFieldCelular.setValue("");
        }
    }//GEN-LAST:event_jFormattedTextFieldCelularFocusLost

    private void jFormattedTextFieldCEPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCEPKeyPressed
        //Verifica se a tecla apertada corresponde ao Enter.
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buscarCep();
        }
    }//GEN-LAST:event_jFormattedTextFieldCEPKeyPressed

    private void jFormattedTextFieldCEPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCEPFocusLost
        if (jFormattedTextFieldCEP.getText().equals("  .   -   ")) {
            jFormattedTextFieldCEP.setValue("");
        }
    }//GEN-LAST:event_jFormattedTextFieldCEPFocusLost

    public void buscarCep() {
        //Faz a busca pelo cep.
        WebServiceCep webServiceCep = WebServiceCep.searchCep(jFormattedTextFieldCEP.getText());
        //A ferramenta de busca ignora qualquer caracter que não seja número.

        //Caso a busca ocorra bem, imprime os resultados.
        if (webServiceCep.wasSuccessful()) {
            jTextFieldLogradouro.setText(webServiceCep.getLogradouroFull());
            jTextFieldCidade.setText(webServiceCep.getCidade());
            jTextFieldBairro.setText(webServiceCep.getBairro());
            jComboBoxEstado.setSelectedItem(webServiceCep.getUf());

            //Caso haja problemas, imprime as excessões.
        } else {
            JOptionPane.showMessageDialog(null, "Erro numero: " + webServiceCep.getResulCode());

            JOptionPane.showMessageDialog(null, "Descrição do erro: " + webServiceCep.getResultText());
        }
    }

    //Limpa os campos da janela.
    public void limparCampos() {
        jComboBoxRelacionamento.setSelectedIndex(0);
        jTextFieldNome.setText("");
        jComboBoxSexo.setSelectedIndex(0);
        jFormattedTextFieldDataNasc.setValue("");
        jComboBoxEstadoCivil.setSelectedIndex(0);
        jFormattedTextFieldEmail.setValue("");
        jFormattedTextFieldResidencial.setValue("");
        jFormattedTextFieldCelular.setValue("");
        jTextFieldProfissao.setText("");
        jFormattedTextFieldCEP.setValue("");
        jTextFieldLogradouro.setText("");
        jTextFieldNumero.setText("");
        jTextFieldBairro.setText("");
        jTextFieldCidade.setText("");
        jTextFieldComplemento.setText("");
        jTextAreaOBS.setText("");
        jTextAreaOBS2.setText("");
    }

    //Carrega os dados do banco na janela para evitar a reinserção de todos os dados.
    public void carregarDados() {
        QueryPessoa query = new QueryPessoa();

        ResultSet rs;
        rs = query.retornarCamposPessoa(item);

        try {
            while (rs.next()) {
                jComboBoxRelacionamento.setSelectedItem(rs.getString("relacionamento_ps"));
                jTextFieldNome.setText(rs.getString("nome_ps"));
                jComboBoxSexo.setSelectedItem(rs.getString("sexo_ps"));
                jFormattedTextFieldDataNasc.setValue(rs.getString("data_nasc_ps"));
                jComboBoxEstadoCivil.setSelectedItem(rs.getString("estado_civil_ps"));
                jFormattedTextFieldEmail.setText(rs.getString("email_ps"));
                jFormattedTextFieldResidencial.setValue(rs.getString("tel_residencial_ps"));
                jFormattedTextFieldCelular.setValue(rs.getString("tel_celular_ps"));
                jTextFieldProfissao.setText(rs.getString("profissao_ps"));
                jFormattedTextFieldCEP.setValue(rs.getString("cep_ps"));
                jTextFieldLogradouro.setText(rs.getString("logradouro_ps"));
                jTextFieldNumero.setText(rs.getString("numero_ps"));
                jTextFieldBairro.setText(rs.getString("bairro_ps"));
                jTextFieldCidade.setText(rs.getString("cidade_ps"));
                jComboBoxEstado.setSelectedItem(rs.getString("estado_ps"));
                jTextFieldComplemento.setText(rs.getString("complemento_ps"));
                jTextAreaOBS.setText(rs.getString("obs_ps"));
                jTextAreaOBS2.setText(rs.getString("obs2_ps"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro de SQL. "
                    + "\nDetalhes: " + ex.getMessage());
        }

        if (jFormattedTextFieldDataNasc.getText().equals("  /  /    ")) {
            jFormattedTextFieldDataNasc.setValue("");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEditarPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEditarPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEditarPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEditarPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEditarPessoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxEstado;
    private javax.swing.JComboBox jComboBoxEstadoCivil;
    private javax.swing.JComboBox jComboBoxRelacionamento;
    private javax.swing.JComboBox jComboBoxSexo;
    private javax.swing.JFormattedTextField jFormattedTextFieldCEP;
    private javax.swing.JFormattedTextField jFormattedTextFieldCelular;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNasc;
    private javax.swing.JFormattedTextField jFormattedTextFieldEmail;
    private javax.swing.JFormattedTextField jFormattedTextFieldResidencial;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCEP;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelComplemento;
    private javax.swing.JLabel jLabelDataNasc;
    private javax.swing.JLabel jLabelEditarPessoa;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelEstadoCivil;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JLabel jLabelLogradouro;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelOBS;
    private javax.swing.JLabel jLabelOBS2;
    private javax.swing.JLabel jLabelProfissao;
    private javax.swing.JLabel jLabelRelacionamento;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelTelefoneCelular;
    private javax.swing.JLabel jLabelTelefoneResidencial;
    private javax.swing.JLabel jLabelVerificaEmail;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextArea jTextAreaOBS;
    private javax.swing.JTextArea jTextAreaOBS2;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldComplemento;
    private javax.swing.JTextField jTextFieldLogradouro;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldProfissao;
    // End of variables declaration//GEN-END:variables
}
