/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Image;
import java.awt.Toolkit;
import java.math.BigInteger;
import java.net.URL;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.JOptionPane;
import jdbc.QueryConfiguracoes;
import operacoes.FixedLengthDocument;

/**
 * @author Gustavo, Ítalo, Juliano e Silas. Descrição: Esta classe tem por
 * propósito mostrar uma janela para criação de usuários. Funções presente:
 * ViewNovoUsuario(); criarUsuario(); main(); Data de criação: 05/09/2015.
 */
public class ViewNovoUsuario extends javax.swing.JFrame {

    /**
     * Creates new form ViewTrocarSenha
     */
    public ViewNovoUsuario() {
        initComponents();
        setLocationRelativeTo(null);  //Centraliza a janela na tela.
        setResizable(false);  //Evita o redimensionamento da janela.

        //Defini o icone da aplicação na barra de tarefas.
        URL url = this.getClass().getResource("icone.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        jTextFieldUsuario.grabFocus();  //Coloca foco no jTextField.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabelImagem = new javax.swing.JLabel();
        jLabelNovoUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new verificacao.VerificarCampo("Numeros/Letras",30);
        jLabelUsuario = new javax.swing.JLabel();
        jLabelPessoa = new javax.swing.JLabel();
        jLabelImagemSenha = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jComboBoxPermissao = new javax.swing.JComboBox();
        jLabelPermissao = new javax.swing.JLabel();
        jLabelImagemPermissao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo usuário");

        jPanel.setBackground(new java.awt.Color(255, 255, 255));
        jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/configuracoes_menor.png"))); // NOI18N
        jPanel.add(jLabelImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 46, -1, -1));

        jLabelNovoUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelNovoUsuario.setText("Novo usuário");
        jPanel.add(jLabelNovoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 69, -1, -1));
        jPanel.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 120, -1));

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelUsuario.setText("Usuário:");
        jPanel.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        jLabelPessoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        jPanel.add(jLabelPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        jLabelImagemSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/senha.png"))); // NOI18N
        jPanel.add(jLabelImagemSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        jLabelSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelSenha.setText("Senha:");
        jPanel.add(jLabelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        jPasswordFieldSenha.setDocument(new FixedLengthDocument(50));
        jPanel.add(jPasswordFieldSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 120, -1));

        jButtonSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanel.add(jButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, -1, -1));

        jButtonLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        jPanel.add(jButtonLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jComboBoxPermissao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Acesso restrito", "Controle total" }));
        jPanel.add(jComboBoxPermissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 120, -1));

        jLabelPermissao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPermissao.setText("Permissão:");
        jPanel.add(jLabelPermissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jLabelImagemPermissao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/permissao.png"))); // NOI18N
        jPanel.add(jLabelImagemPermissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        criarUsuario();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();  //Fecha a janela atual.
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        //Limpa os campos do form.        
        jTextFieldUsuario.setText("");
        jPasswordFieldSenha.setText("");
        //Da foco no jTextField.
        jTextFieldUsuario.grabFocus();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    public void criarUsuario() {
        QueryConfiguracoes query = new QueryConfiguracoes();

        String senha = new String(jPasswordFieldSenha.getPassword());

        //Verifica se o campo usuário não está em branco e se a senha digitada tem no mínimo 8 caracteres.
        if (!jTextFieldUsuario.getText().trim().equals("") && senha.length() >= 8) {

            if (query.verificarUsuario(jTextFieldUsuario.getText()) == false) {

                try {
                    MessageDigest md = MessageDigest.getInstance("MD5");
                    md.update(senha.getBytes());
                    String td = new BigInteger(1, md.digest()).toString(16);

                    query.inserirUsuario("1", jTextFieldUsuario.getText(), td,
                            jComboBoxPermissao.getSelectedItem().toString());

                    dispose();  //Fecha a janela atual.
                } catch (NoSuchAlgorithmException ex) {
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro no algoritmo de criptografia. "
                            + "\nDetalhes: " + ex.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(null, "O nome de usuário digitado já está em uso.");
                jTextFieldUsuario.setText("");
                jTextFieldUsuario.grabFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "O campo usuário está em branco ou a senha inserida possui menos de 8 caracteres."
                    + "\nPor favor, verifique essas condições.");
            jPasswordFieldSenha.setText("");
            jPasswordFieldSenha.grabFocus();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewNovoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewNovoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewNovoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewNovoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewNovoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxPermissao;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JLabel jLabelImagemPermissao;
    private javax.swing.JLabel jLabelImagemSenha;
    private javax.swing.JLabel jLabelNovoUsuario;
    private javax.swing.JLabel jLabelPermissao;
    private javax.swing.JLabel jLabelPessoa;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
