/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;
import jdbc.QueryConfiguracoes;
import pessoa.UsuarioAtual;

/**
 * @author Gustavo, Ítalo, Juliano e Silas. Descrição: Esta classe tem por
 * propósito mostrar uma janela com algumas informações de ajuda. Funções
 * presente: ViewConfiguracoes(); verificarUsuarioIncluir();
 * verificarUsuarioExcluir(); verificarUsuarioVisualizar(); main(); Data de
 * criação: 05/09/2015.
 */
public class ViewConfiguracoes extends javax.swing.JFrame {

    QueryConfiguracoes query = new QueryConfiguracoes();
    UsuarioAtual usuario = new UsuarioAtual();

    /**
     * Creates new form ViewConfiguracoes
     */
    public ViewConfiguracoes() {
        initComponents();
        setLocationRelativeTo(null);  //Centraliza a janela na tela.
        setResizable(false);  //Evita o redimensionamento da janela.

        //Defini o icone da aplicação na barra de tarefas.
        URL url = this.getClass().getResource("icone.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jButtonFechar = new javax.swing.JButton();
        jButtonRemoverUsuario = new javax.swing.JButton();
        jLabelImagemConfiguracoes = new javax.swing.JLabel();
        jButtonSenha = new javax.swing.JButton();
        jLabelConfiguracoes = new javax.swing.JLabel();
        jButtonNovoUsuario = new javax.swing.JButton();
        jButtonUsuariosCadastrados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configurações");

        jPanel.setBackground(new java.awt.Color(255, 255, 255));

        jButtonFechar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fechar.png"))); // NOI18N
        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jButtonRemoverUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonRemoverUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        jButtonRemoverUsuario.setText("Remover usuário");
        jButtonRemoverUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverUsuarioActionPerformed(evt);
            }
        });

        jLabelImagemConfiguracoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/configuracoes_menor.png"))); // NOI18N

        jButtonSenha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/senha.png"))); // NOI18N
        jButtonSenha.setText("Trocar senha");
        jButtonSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSenhaActionPerformed(evt);
            }
        });

        jLabelConfiguracoes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelConfiguracoes.setText("Configurações");

        jButtonNovoUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNovoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        jButtonNovoUsuario.setText("Adicionar novo usuário");
        jButtonNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoUsuarioActionPerformed(evt);
            }
        });

        jButtonUsuariosCadastrados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonUsuariosCadastrados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        jButtonUsuariosCadastrados.setText("Usuários cadastrados");
        jButtonUsuariosCadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuariosCadastradosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jButtonNovoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUsuariosCadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jButtonRemoverUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jButtonFechar))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jLabelImagemConfiguracoes)
                        .addGap(10, 10, 10)
                        .addComponent(jLabelConfiguracoes)))
                .addGap(32, 32, 32))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelImagemConfiguracoes)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabelConfiguracoes)))
                .addGap(49, 49, 49)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNovoUsuario)
                    .addComponent(jButtonUsuariosCadastrados))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRemoverUsuario)
                    .addComponent(jButtonSenha))
                .addGap(34, 34, 34)
                .addComponent(jButtonFechar)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRemoverUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverUsuarioActionPerformed
        verificarUsuarioExcluir();
    }//GEN-LAST:event_jButtonRemoverUsuarioActionPerformed

    private void jButtonSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSenhaActionPerformed
        ViewTrocarSenha view = new ViewTrocarSenha();
        view.setVisible(true);
    }//GEN-LAST:event_jButtonSenhaActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        dispose();  //Fecha a janela atual.
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoUsuarioActionPerformed
        verificarUsuarioIncluir();
    }//GEN-LAST:event_jButtonNovoUsuarioActionPerformed

    private void jButtonUsuariosCadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuariosCadastradosActionPerformed
        verificarUsuarioVisualizar();
    }//GEN-LAST:event_jButtonUsuariosCadastradosActionPerformed

    //Verifica se o usuário logado tem permissão para incluir/exluir/visualizar outros usuários.
    public void verificarUsuarioIncluir() {

        if (query.verificarPermissao(usuario.getUsuarioAtual()) == true) {
            ViewNovoUsuario view = new ViewNovoUsuario();
            view.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão para realizar esta ação.");
        }
    }

    public void verificarUsuarioExcluir() {
        if (query.verificarPermissao(usuario.getUsuarioAtual()) == true) {
            ViewRemoverUsuario view = new ViewRemoverUsuario();
            view.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão para realizar esta ação.");
        }
    }

    public void verificarUsuarioVisualizar() {
        if (query.verificarPermissao(usuario.getUsuarioAtual()) == true) {
            ViewMostrarUsuario view = new ViewMostrarUsuario();
            view.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão para realizar esta ação.");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewConfiguracoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonNovoUsuario;
    private javax.swing.JButton jButtonRemoverUsuario;
    private javax.swing.JButton jButtonSenha;
    private javax.swing.JButton jButtonUsuariosCadastrados;
    private javax.swing.JLabel jLabelConfiguracoes;
    private javax.swing.JLabel jLabelImagemConfiguracoes;
    private javax.swing.JPanel jPanel;
    // End of variables declaration//GEN-END:variables
}
